class Lgpkg {
  String currentLanguage = "English";

  static const Map<String, Map<String, String>> _localizedValues = {

    // --- English ---
    "English": {
      // Top Navigation
      "AppTitle": "EDEN Client",
      "PlayTitle": "PLAY",
      "SocialTitle": "Social",
      "ProConfigTitle": "PRO Config",
      "MarketplaceTitle": "MARKETPLACE",
      "Play": "PLAY",
      
      // Game Modes
      "Matchmaking": "MATCHMAKING",
      "Tournaments": "TOURNAMENTS",
      "Deathmatch": "DEATHMATCH",
      "1v1Hubs": "1V1 HUBS",
      
      // Status & Engine
      "Status": "Status",
      "Idle": "Idle",
      "WaitingAction": "WAITING FOR ACTION",
      "InitializingAC": "INITIALIZING AC...",
      "ACActive": "ANTI-CHEAT ACTIVE",
      "EdenACActive": "EDEN AC ACTIVE",
      "TunnelSecured": "SECURED",
      "TunnelWaiting": "WAITING",
      "SessionConnected": "CONNECTED",
      "SessionIdle": "IDLE",
      "AntiCheat": "ANTI-CHEAT",
      
      // Match Flow
      "StartMatching": "START MATCHING",
      "CancelMatching": "CANCEL MATCHING",
      "Searching": "SEARCHING",
      "SearchingMsg": "SEARCHING FOR MATCH...",
      "MatchFound": "MATCH FOUND!",
      "MatchCancelled": "MATCH CANCELLED",
      "StopServer": "STOP SERVER",
      "StartingServer": "STARTING SERVER",
      "ServerOnline": "SERVER ONLINE (WAITING)",
      "CreateCustomLobby": "CREATE CUSTOM LOBBY",
      "CancelSearch": "CANCEL SEARCH",
      
      // In-Game/Scoreboard
      "Score": "Score",
      "Warmup": "WARMUP",
      "HalfTime": "HALF TIME",
      "Final": "FINAL",
      "MatchEndedMining": "Match Ended. Mining Block...",
      "Lobby": "LOBBY",
      "TeamRoster": "TEAM ROSTER",
      "VS": "VS",
      "EmptySlot": "Empty Slot",
      
      // Errors & Dialogs
      "ConfigError": "CONFIG ERROR",
      "ConfigWriteError": "Could not write GSI config.",
      "ACRequired": "ANTI-CHEAT REQUIRED",
      "ShieldRequiredMsg": "Active Shield required to host games.",
      "EnableShieldMsg": "You must enable the Eden Anti-Cheat shield.",
      "InsufficientFunds": "INSUFFICIENT FUNDS",
      "TransactionFailed": "TRANSACTION FAILED",
      "ProcessDeductionFailed": "Could not process deduction.",
      "Error": "Error",
      "OK": "OK",
      "Cancel": "CANCEL",
      "Close": "CLOSE",
      "Loading": "LOADING",
      
      // Friends & Social
      "FriendsList": "FRIENDS LIST",
      "AddFriend": "ADD FRIEND",
      "EnterFriendCode": "Enter Friend Code / Peer ID",
      "NoFriendsMsg": "No friends yet. Add one using their Peer ID.",
      "Invite": "INVITE",
      "InvitedMsg": "Invited to Lobby",
      "Trade": "TRADE",
      "FriendCode": "FRIEND CODE",
      "PeerID": "PEER ID",
      "Level": "LEVEL",
      "Skill": "Skill",
      "IncomingRequest": "Incoming Friend Request",
      "RequestSent": "Request Sent - Waiting...",
      "Pending": "PENDING",
      "Offline": "Offline",
      
      // Profile
      "ChangeIdentity": "CHANGE IDENTITY",
      "ChangeIdentityCost": "Changing your platform alias costs 10 EDN.",
      "NewAlias": "New Alias",
      "Pay10EDN": "PAY 10 EDN",
      
      // Wallet
      "EdenWallet": "EDEN WALLET",
      "LiveBalance": "Live Balance",
      "Send": "SEND",
      "Receive": "RECEIVE",
      "SendEDN": "SEND EDN",
      "ReceiveEDN": "RECEIVE EDN",
      "ReceiverID": "Receiver Peer ID",
      "Amount": "Amount",
      "ShareIDMsg": "Share this Peer ID to receive funds:",
      "Copy": "COPY",
      "MiningRewardsMsg": "Mining rewards are deposited after every match.",
      "TransferFailed": "Transfer Failed.",
      "CopiedClipboard": "Copied to Clipboard",
      
      // Trade Overlay
      "SecureTradeOffer": "SECURE TRADE OFFER",
      "Holdings": "Holdings",
      "EstRemaining": "Est. Remaining:",
      "EstTotal": "Est. Total:",
      "TradingAmount": "TRADING AMOUNT",
      "CancelTrade": "CANCEL TRADE",
      "ConfirmAccept": "CONFIRM & ACCEPT",
      "TradeSuccessful": "Trade Successful!",
      "TradeFailed": "Trade Failed.",
      
      // Marketplace & Betting
      "AuctionTab": "AUCTION",
      "BetTab": "BET",
      "GlobalMarket": "GLOBAL MARKET",
      "SellItemBtn": "SELL ITEM",
      "NoListingsMsg": "No active listings found on the chain.",
      "NoLiveMatches": "No live matches found.",
      "BroadcastMsg": "Servers broadcast automatically when live.",
      "LiveTag": "LIVE",
      "YouTag": "YOU",
      "ListedBtn": "LISTED",
      "BuyNowBtn": "BUY NOW",
      "SelectItemToSell": "Select Item to Sell",
      "ListItemBtn": "LIST ITEM",
      "Price": "Price",
      "Duration": "Duration (seconds)",
      "BetPlaced": "Bet Placed!",
      "BetFailed": "Bet Failed",
      "SyncwithBlockchain": "Sync with Blockchain",

      // Stats & Demo
      "MatchHistory": "MATCH HISTORY",
      "AnalyzeDemoBtn": "ANALYZE NEW DEMO",
      "SelectMatchTitle": "SELECT A MATCH",
      "SelectMatchMsg": "Select a match from the left to view detailed analytics",
      "Scoreboard": "SCOREBOARD",
      "DownloadDemo": "DOWNLOAD DEMO",
      "WatchRoom": "WATCH ROOM",
      "HeaderPlayer": "PLAYER",
      "HeaderKills": "KILLS",
      "HeaderDeaths": "DEATHS",
      "HeaderKD": "K/D",
      "HeaderADR": "ADR",
      "HeaderRating": "RATING",
      "MatchAnalyzed": "MATCH ANALYZED",
      "AnalysisFailed": "Analysis Failed",
      
      // Settings
      "Settings": "SETTINGS",
      "CS2Path": "CS2 Installation Path",
      "CSGOPath": "CSGO Installation Path",
      "Steam64ID": "Steam 64 ID (For Trade)",
      "SteamAPIKey": "Steam Web API Key",
      "DBUser": "Database User",
      "DBPassword": "Database Password",
      "LanguageLabel": "Language",
      "Save": "SAVE",
      "Submit": "SUBMIT",
      "SettingsSavedMsg": "Settings Saved. Restart app for changes.",
      "MapSelection": "MAP SELECTION",
      "PasteHubID": "MatchID@HostPeerID",
      "Map": "Map",
      "Connect": "CONNECT",
    },
    
    // --- Chinese (Simplified) ---
    "Chinese": {
      "AppTitle": "EDEN客户端",
      "PlayTitle": "开始游戏",
      "SocialTitle": "社交",
      "ProConfigTitle": "职业配置",
      "MarketplaceTitle": "市场",
      "Play": "开始",
      "Matchmaking": "排位赛",
      "Tournaments": "锦标赛",
      "Deathmatch": "死斗模式",
      "1v1Hubs": "单挑模式",
      "Status": "状态",
      "Idle": "空闲",
      "WaitingAction": "等待操作",
      "InitializingAC": "正在初始化反作弊...",
      "ACActive": "反作弊已激活",
      "EdenACActive": "EDEN反作弊运行中",
      "TunnelSecured": "安全",
      "TunnelWaiting": "等待中",
      "SessionConnected": "已连接",
      "SessionIdle": "空闲",
      "AntiCheat": "反作弊",
      "StartMatching": "开始匹配",
      "CancelMatching": "取消匹配",
      "Searching": "搜索中",
      "SearchingMsg": "正在寻找比赛...",
      "MatchFound": "找到比赛!",
      "MatchCancelled": "比赛取消",
      "StopServer": "停止服务器",
      "StartingServer": "正在启动服务器",
      "ServerOnline": "服务器在线 (等待中)",
      "CreateCustomLobby": "创建自定义房间",
      "CancelSearch": "取消搜索",
      "Score": "分数",
      "Warmup": "热身",
      "HalfTime": "半场",
      "Final": "最终",
      "MatchEndedMining": "比赛结束. 正在挖掘区块...",
      "Lobby": "大厅",
      "TeamRoster": "队伍名单",
      "VS": "VS",
      "EmptySlot": "空位",
      "ConfigError": "配置错误",
      "ConfigWriteError": "无法写入GSI配置.",
      "ACRequired": "需要反作弊",
      "ShieldRequiredMsg": "主机游戏需要激活护盾.",
      "EnableShieldMsg": "您必须启用Eden反作弊护盾.",
      "InsufficientFunds": "资金不足",
      "TransactionFailed": "交易失败",
      "ProcessDeductionFailed": "无法处理扣款.",
      "Error": "错误",
      "OK": "确定",
      "Cancel": "取消",
      "Close": "关闭",
      "Loading": "加载中",
      "FriendsList": "好友列表",
      "AddFriend": "添加好友",
      "EnterFriendCode": "输入好友代码 / Peer ID",
      "NoFriendsMsg": "暂无好友. 使用ID添加.",
      "Invite": "邀请",
      "InvitedMsg": "已邀请至大厅",
      "Trade": "交易",
      "FriendCode": "好友代码",
      "PeerID": "PEER ID",
      "Level": "等级",
      "Skill": "技术分",
      "IncomingRequest": "好友请求",
      "RequestSent": "请求已发送",
      "Pending": "等待中",
      "Offline": "离线",
      "ChangeIdentity": "更改身份",
      "ChangeIdentityCost": "更改平台别名需花费 10 EDN.",
      "NewAlias": "新别名",
      "Pay10EDN": "支付 10 EDN",
      "EdenWallet": "EDEN 钱包",
      "LiveBalance": "实时余额",
      "Send": "发送",
      "Receive": "接收",
      "SendEDN": "发送 EDN",
      "ReceiveEDN": "接收 EDN",
      "ReceiverID": "接收者 Peer ID",
      "Amount": "数量",
      "ShareIDMsg": "分享此ID以接收资金:",
      "Copy": "复制",
      "MiningRewardsMsg": "比赛结束后发放挖矿奖励.",
      "TransferFailed": "转账失败.",
      "CopiedClipboard": "已复制到剪贴板",
      "SecureTradeOffer": "安全交易提议",
      "Holdings": "持有量",
      "EstRemaining": "预计剩余:",
      "EstTotal": "预计总计:",
      "TradingAmount": "交易数量",
      "CancelTrade": "取消交易",
      "ConfirmAccept": "确认并接受",
      "TradeSuccessful": "交易成功!",
      "TradeFailed": "交易失败.",
      "AuctionTab": "拍卖",
      "BetTab": "博彩",
      "SyncwithBlockchain": "与区块链同步",
      "GlobalMarket": "全球市场",
      "SellItemBtn": "出售物品",
      "NoListingsMsg": "链上暂无活跃列表.",
      "NoLiveMatches": "暂无直播比赛.",
      "BroadcastMsg": "服务器在直播时会自动广播.",
      "LiveTag": "直播",
      "YouTag": "你",
      "ListedBtn": "已上架",
      "BuyNowBtn": "立即购买",
      "SelectItemToSell": "选择出售物品",
      "ListItemBtn": "上架物品",
      "Price": "价格",
      "Duration": "持续时间 (秒)",
      "BetPlaced": "下注成功!",
      "BetFailed": "下注失败",
      "MatchHistory": "比赛历史",
      "AnalyzeDemoBtn": "分析新DEMO",
      "SelectMatchTitle": "选择比赛",
      "SelectMatchMsg": "从左侧选择比赛以查看详细分析",
      "Scoreboard": "记分板",
      "DownloadDemo": "下载DEMO",
      "WatchRoom": "观看房间",
      "HeaderPlayer": "玩家",
      "HeaderKills": "击杀",
      "HeaderDeaths": "死亡",
      "HeaderKD": "K/D",
      "HeaderADR": "ADR",
      "HeaderRating": "评分",
      "MatchAnalyzed": "比赛已分析",
      "AnalysisFailed": "分析失败",
      "Settings": "设置",
      "CS2Path": "CS2 安装路径",
      "CSGOPath": "CSGO 安装路径",
      "Steam64ID": "Steam 64位 ID (交易用)",
      "SteamAPIKey": "Steam Web API 密钥",
      "DBUser": "数据库用户",
      "DBPassword": "数据库密码",
      "LanguageLabel": "语言",
      "Save": "保存",
      "Submit": "提交",
      "SettingsSavedMsg": "设置已保存. 重启应用生效.",
      "MapSelection": "地图选择",
      "PasteHubID": "MatchID@HostPeerID",
      "Map": "地图",
      "Connect": "连接",
    },

    // --- Russian ---
    "Russian": {
      "AppTitle": "Клиент EDEN",
      "PlayTitle": "ИГРАТЬ",
      "SocialTitle": "Сообщество",
      "ProConfigTitle": "PRO Конфиг",
      "MarketplaceTitle": "ТОРГОВАЯ ПЛОЩАДКА",
      "Play": "ИГРАТЬ",
      "Matchmaking": "ПОИСК ИГРЫ",
      "Tournaments": "ТУРНИРЫ",
      "Deathmatch": "БОЙ НАСМЕРТЬ",
      "1v1Hubs": "1V1 ХАБЫ",
      "Status": "Статус",
      "Idle": "Ожидание",
      "WaitingAction": "ОЖИДАНИЕ ДЕЙСТВИЯ",
      "InitializingAC": "ЗАПУСК АНТИЧИТА...",
      "ACActive": "АНТИЧИТ АКТИВЕН",
      "EdenACActive": "EDEN AC РАБОТАЕТ",
      "TunnelSecured": "ЗАЩИЩЕНО",
      "TunnelWaiting": "ОЖИДАНИЕ",
      "SessionConnected": "ПОДКЛЮЧЕНО",
      "SessionIdle": "ПРОСТОЙ",
      "AntiCheat": "АНТИЧИТ",
      "StartMatching": "НАЧАТЬ ПОИСК",
      "CancelMatching": "ОТМЕНА ПОИСКА",
      "Searching": "ПОИСК",
      "SearchingMsg": "ПОИСК МАТЧА...",
      "MatchFound": "МАТЧ НАЙДЕН!",
      "MatchCancelled": "МАТЧ ОТМЕНЕН",
      "StopServer": "ОСТАНОВИТЬ СЕРВЕР",
      "StartingServer": "ЗАПУСК СЕРВЕРА",
      "ServerOnline": "СЕРВЕР ОНЛАЙН (ОЖИДАНИЕ)",
      "CreateCustomLobby": "СОЗДАТЬ СВОЕ ЛОББИ",
      "CancelSearch": "ОТМЕНИТЬ",
      "Score": "Счет",
      "Warmup": "РАЗМИНКА",
      "HalfTime": "ПЕРЕРЫВ",
      "Final": "ФИНАЛ",
      "MatchEndedMining": "Матч завершен. Майнинг блока...",
      "Lobby": "ЛОББИ",
      "TeamRoster": "СОСТАВ КОМАНДЫ",
      "VS": "VS",
      "EmptySlot": "Пустой слот",
      "ConfigError": "ОШИБКА КОНФИГА",
      "ConfigWriteError": "Не удалось записать GSI конфиг.",
      "ACRequired": "ТРЕБУЕТСЯ АНТИЧИТ",
      "ShieldRequiredMsg": "Активный Shield нужен для хостинга.",
      "EnableShieldMsg": "Вы должны включить Eden Anti-Cheat.",
      "InsufficientFunds": "НЕДОСТАТОЧНО СРЕДСТВ",
      "TransactionFailed": "ОШИБКА ТРАНЗАКЦИИ",
      "ProcessDeductionFailed": "Не удалось списать средства.",
      "Error": "Ошибка",
      "OK": "ОК",
      "Cancel": "ОТМЕНА",
      "Close": "ЗАКРЫТЬ",
      "Loading": "ЗАГРУЗКА",
      "FriendsList": "СПИСОК ДРУЗЕЙ",
      "AddFriend": "ДОБАВИТЬ ДРУГА",
      "EnterFriendCode": "Введите код друга / Peer ID",
      "NoFriendsMsg": "Нет друзей. Добавьте по Peer ID.",
      "Invite": "ПРИГЛАСИТЬ",
      "InvitedMsg": "Приглашен в лобби",
      "Trade": "ОБМЕН",
      "FriendCode": "КОД ДРУГА",
      "PeerID": "PEER ID",
      "Level": "УРОВЕНЬ",
      "Skill": "Навык",
      "IncomingRequest": "Входящий запрос",
      "RequestSent": "Запрос отправлен...",
      "Pending": "ОЖИДАНИЕ",
      "Offline": "Оффлайн",
      "ChangeIdentity": "СМЕНИТЬ ЛИЧНОСТЬ",
      "ChangeIdentityCost": "Смена псевдонима стоит 10 EDN.",
      "NewAlias": "Новый псевдоним",
      "Pay10EDN": "ОПЛАТИТЬ 10 EDN",
      "EdenWallet": "КОШЕЛЕК EDEN",
      "LiveBalance": "Текущий баланс",
      "Send": "ОТПРАВИТЬ",
      "Receive": "ПОЛУЧИТЬ",
      "SendEDN": "ОТПРАВИТЬ EDN",
      "ReceiveEDN": "ПОЛУЧИТЬ EDN",
      "ReceiverID": "Peer ID получателя",
      "Amount": "Сумма",
      "ShareIDMsg": "Поделитесь этим ID для получения средств:",
      "Copy": "КОПИРОВАТЬ",
      "MiningRewardsMsg": "Награды за майнинг приходят после матча.",
      "TransferFailed": "Перевод не удался.",
      "CopiedClipboard": "Скопировано в буфер обмена",
      "SecureTradeOffer": "БЕЗОПАСНЫЙ ОБМЕН",
      "Holdings": "Баланс",
      "EstRemaining": "Ост. (прибл.):",
      "EstTotal": "Итого (прибл.):",
      "TradingAmount": "СУММА ОБМЕНА",
      "CancelTrade": "ОТМЕНИТЬ",
      "ConfirmAccept": "ПОДТВЕРДИТЬ",
      "TradeSuccessful": "Обмен успешен!",
      "TradeFailed": "Обмен не удался.",
      "AuctionTab": "АУКЦИОН",
      "BetTab": "СТАВКИ",
      "SyncwithBlockchain": "Синхронизация с блокчейном",
      "GlobalMarket": "ГЛОБАЛЬНЫЙ РЫНОК",
      "SellItemBtn": "ПРОДАТЬ ПРЕДМЕТ",
      "NoListingsMsg": "Нет активных лотов в блокчейне.",
      "NoLiveMatches": "Нет прямых трансляций матчей.",
      "BroadcastMsg": "Серверы транслируют матчи автоматически.",
      "LiveTag": "LIVE",
      "YouTag": "ВЫ",
      "ListedBtn": "В ПРОДАЖЕ",
      "BuyNowBtn": "КУПИТЬ",
      "SelectItemToSell": "Выберите предмет для продажи",
      "ListItemBtn": "ВЫСТАВИТЬ",
      "Price": "Цена",
      "Duration": "Длительность (сек)",
      "BetPlaced": "Ставка принята!",
      "BetFailed": "Ошибка ставки",
      "MatchHistory": "ИСТОРИЯ МАТЧЕЙ",
      "AnalyzeDemoBtn": "АНАЛИЗ НОВОГО ДЕМО",
      "SelectMatchTitle": "ВЫБЕРИТЕ МАТЧ",
      "SelectMatchMsg": "Выберите матч слева для детальной аналитики",
      "Scoreboard": "ТАБЛИЦА РЕЗУЛЬТАТОВ",
      "DownloadDemo": "СКАЧАТЬ ДЕМО",
      "WatchRoom": "СМОТРЕТЬ",
      "HeaderPlayer": "ИГРОК",
      "HeaderKills": "УБИЙСТВА",
      "HeaderDeaths": "СМЕРТИ",
      "HeaderKD": "K/D",
      "HeaderADR": "ADR",
      "HeaderRating": "РЕЙТИНГ",
      "MatchAnalyzed": "МАТЧ ПРОАНАЛИЗИРОВАН",
      "AnalysisFailed": "Ошибка анализа",
      "Settings": "НАСТРОЙКИ",
      "CS2Path": "Путь к CS2",
      "CSGOPath": "Путь к CSGO",
      "Steam64ID": "Steam 64 ID (Для обмена)",
      "SteamAPIKey": "Steam Web API Key",
      "DBUser": "Пользователь БД",
      "DBPassword": "Пароль БД",
      "LanguageLabel": "Язык",
      "Save": "СОХРАНИТЬ",
      "Submit": "ПРИМЕНИТЬ",
      "SettingsSavedMsg": "Настройки сохранены. Перезапустите приложение.",
      "MapSelection": "ВЫБОР КАРТЫ",
      "PasteHubID": "MatchID@HostPeerID",
      "Map": "Карта",
      "Connect": "ПОДКЛЮЧИТЬСЯ",
    },

    // --- Ukrainian ---
    "Ukrainian": {
      "AppTitle": "Клієнт EDEN",
      "PlayTitle": "ГРАТИ",
      "SocialTitle": "Спільнота",
      "ProConfigTitle": "PRO Конфіг",
      "MarketplaceTitle": "РИНОК",
      "Play": "ГРАТИ",
      "Matchmaking": "ПОШУК ГРИ",
      "Tournaments": "ТУРНІРИ",
      "Deathmatch": "БІЙ НАСМЕРТЬ",
      "1v1Hubs": "1V1 ХАБИ",
      "Status": "Статус",
      "Idle": "Очікування",
      "WaitingAction": "ОЧІКУВАННЯ ДІЇ",
      "InitializingAC": "ЗАПУСК АНТИЧІТУ...",
      "ACActive": "АНТИЧІТ АКТИВНИЙ",
      "EdenACActive": "EDEN AC ПРАЦЮЄ",
      "TunnelSecured": "ЗАХИЩЕНО",
      "TunnelWaiting": "ОЧІКУВАННЯ",
      "SessionConnected": "ПІДКЛЮЧЕНО",
      "SessionIdle": "ПРОСТІЙ",
      "AntiCheat": "АНТИЧІТ",
      "StartMatching": "ПОЧАТИ ПОШУК",
      "CancelMatching": "СКАСУВАТИ ПОШУК",
      "Searching": "ПОШУК",
      "SearchingMsg": "ПОШУК МАТЧУ...",
      "MatchFound": "МАТЧ ЗНАЙДЕНО!",
      "MatchCancelled": "МАТЧ СКАСОВАНО",
      "StopServer": "ЗУПИНИТИ СЕРВЕР",
      "StartingServer": "ЗАПУСК СЕРВЕРА",
      "ServerOnline": "СЕРВЕР ОНЛАЙН (ОЧІКУВАННЯ)",
      "CreateCustomLobby": "СТВОРИТИ ЛОБІ",
      "CancelSearch": "СКАСУВАТИ",
      "Score": "Рахунок",
      "Warmup": "РОЗМИНКА",
      "HalfTime": "ПЕРЕРВА",
      "Final": "ФІНАЛ",
      "MatchEndedMining": "Матч завершено. Майнінг блоку...",
      "Lobby": "ЛОБІ",
      "TeamRoster": "СКЛАД КОМАНДИ",
      "VS": "VS",
      "EmptySlot": "Вільний слот",
      "ConfigError": "ПОМИЛКА КОНФІГУ",
      "ConfigWriteError": "Не вдалося записати GSI конфіг.",
      "ACRequired": "ПОТРІБЕН АНТИЧІТ",
      "ShieldRequiredMsg": "Активний Shield потрібен для хостингу.",
      "EnableShieldMsg": "Ви повинні увімкнути Eden Anti-Cheat.",
      "InsufficientFunds": "НЕДОСТАТНЬО КОШТІВ",
      "TransactionFailed": "ПОМИЛКА ТРАНЗАКЦІЇ",
      "ProcessDeductionFailed": "Не вдалося списати кошти.",
      "Error": "Помилка",
      "OK": "ОК",
      "Cancel": "СКАСУВАТИ",
      "Close": "ЗАКРИТИ",
      "Loading": "ЗАВАНТАЖЕННЯ",
      "FriendsList": "СПИСОК ДРУЗІВ",
      "AddFriend": "ДОДАТИ ДРУГА",
      "EnterFriendCode": "Введіть код друга / Peer ID",
      "NoFriendsMsg": "Немає друзів. Додайте за Peer ID.",
      "Invite": "ЗАПРОСИТИ",
      "InvitedMsg": "Запрошено в лобі",
      "Trade": "ОБМІН",
      "FriendCode": "КОД ДРУГА",
      "PeerID": "PEER ID",
      "Level": "РІВЕНЬ",
      "Skill": "Навичка",
      "IncomingRequest": "Вхідний запит",
      "RequestSent": "Запит надіслано...",
      "Pending": "ОЧІКУВАННЯ",
      "Offline": "Офлайн",
      "ChangeIdentity": "ЗМІНИТИ ОСОБИСТІСТЬ",
      "ChangeIdentityCost": "Зміна псевдоніма коштує 10 EDN.",
      "NewAlias": "Новий псевдонім",
      "Pay10EDN": "ОПЛАТИТИ 10 EDN",
      "EdenWallet": "ГАМАНЕЦЬ EDEN",
      "LiveBalance": "Поточний баланс",
      "Send": "НАДІСЛАТИ",
      "Receive": "ОТРИМАТИ",
      "SendEDN": "НАДІСЛАТИ EDN",
      "ReceiveEDN": "ОТРИМАТИ EDN",
      "ReceiverID": "Peer ID отримувача",
      "Amount": "Сума",
      "ShareIDMsg": "Поділіться цим ID для отримання коштів:",
      "Copy": "КОПІЮВАТИ",
      "MiningRewardsMsg": "Нагороди за майнінг надходять після матчу.",
      "TransferFailed": "Переказ не вдався.",
      "CopiedClipboard": "Скопійовано в буфер обміну",
      "SecureTradeOffer": "БЕЗПЕЧНИЙ ОБМІН",
      "Holdings": "Баланс",
      "EstRemaining": "Зал. (прибл.):",
      "EstTotal": "Разом (прибл.):",
      "TradingAmount": "СУМА ОБМІНУ",
      "CancelTrade": "СКАСУВАТИ",
      "ConfirmAccept": "ПІДТВЕРДИТИ",
      "TradeSuccessful": "Обмін успішний!",
      "TradeFailed": "Обмін не вдався.",
      "AuctionTab": "АУКЦІОН",
      "BetTab": "СТАВКИ",
      "SyncwithBlockchain": "Синхронізація з блокчейном",
      "GlobalMarket": "ГЛОБАЛЬНИЙ РИНОК",
      "SellItemBtn": "ПРОДАТИ ПРЕДМЕТ",
      "NoListingsMsg": "Немає активних лотів у блокчейні.",
      "NoLiveMatches": "Немає прямих трансляцій матчів.",
      "BroadcastMsg": "Сервери транслюють матчі автоматично.",
      "LiveTag": "LIVE",
      "YouTag": "ВИ",
      "ListedBtn": "У ПРОДАЖУ",
      "BuyNowBtn": "КУПИТИ",
      "SelectItemToSell": "Виберіть предмет для продажу",
      "ListItemBtn": "ВИСТАВИТИ",
      "Price": "Ціна",
      "Duration": "Тривалість (сек)",
      "BetPlaced": "Ставку прийнято!",
      "BetFailed": "Помилка ставки",
      "MatchHistory": "ІСТОРІЯ МАТЧІВ",
      "AnalyzeDemoBtn": "АНАЛІЗ НОВОГО ДЕМО",
      "SelectMatchTitle": "ВИБЕРІТЬ МАТЧ",
      "SelectMatchMsg": "Виберіть матч зліва для детальної аналітики",
      "Scoreboard": "ТАБЛИЦЯ РЕЗУЛЬТАТІВ",
      "DownloadDemo": "ЗАВАНТАЖИТИ ДЕМО",
      "WatchRoom": "ДИВИТИСЯ",
      "HeaderPlayer": "ГРАВЕЦЬ",
      "HeaderKills": "ВБИВСТВА",
      "HeaderDeaths": "СМЕРТІ",
      "HeaderKD": "K/D",
      "HeaderADR": "ADR",
      "HeaderRating": "РЕЙТИНГ",
      "MatchAnalyzed": "МАТЧ ПРОАНАЛІЗОВАНО",
      "AnalysisFailed": "Помилка аналізу",
      "Settings": "НАЛАШТУВАННЯ",
      "CS2Path": "Шлях до CS2",
      "CSGOPath": "Шлях до CSGO",
      "Steam64ID": "Steam 64 ID (Для обміну)",
      "SteamAPIKey": "Steam Web API Key",
      "DBUser": "Користувач БД",
      "DBPassword": "Пароль БД",
      "LanguageLabel": "Мова",
      "Save": "ЗБЕРЕГТИ",
      "Submit": "ЗАСТОСУВАТИ",
      "SettingsSavedMsg": "Налаштування збережено. Перезапустіть додаток.",
      "MapSelection": "ВИБІР МАПИ",
      "PasteHubID": "MatchID@HostPeerID",
      "Map": "Мапа",
      "Connect": "ПІДКЛЮЧИТИСЯ",
    },

    // --- Polish ---
    "Polish": {
      "AppTitle": "Klient EDEN",
      "PlayTitle": "GRAJ",
      "SocialTitle": "Społeczność",
      "ProConfigTitle": "Konfiguracja PRO",
      "MarketplaceTitle": "RYNEK",
      "Play": "GRAJ",
      "Matchmaking": "MATCHMAKING",
      "Tournaments": "TURNIEJE",
      "Deathmatch": "DEATHMATCH",
      "1v1Hubs": "HUBY 1V1",
      "Status": "Status",
      "Idle": "Bezczynny",
      "WaitingAction": "OCZEKIWANIE NA AKCJĘ",
      "InitializingAC": "INICJOWANIE ANTY-CHEATA...",
      "ACActive": "ANTY-CHEAT AKTYWNY",
      "EdenACActive": "EDEN AC DZIAŁA",
      "TunnelSecured": "ZABEZPIECZONY",
      "TunnelWaiting": "OCZEKIWANIE",
      "SessionConnected": "POŁĄCZONO",
      "SessionIdle": "BEZCZYNNY",
      "AntiCheat": "ANTY-CHEAT",
      "StartMatching": "SZUKAJ GRY",
      "CancelMatching": "ANULUJ SZUKANIE",
      "Searching": "WYSZUKIWANIE",
      "SearchingMsg": "SZUKANIE MECZU...",
      "MatchFound": "MECZ ZNALEZIONY!",
      "MatchCancelled": "MECZ ANULOWANY",
      "StopServer": "ZATRZYMAJ SERWER",
      "StartingServer": "URUCHAMIANIE SERWERA",
      "ServerOnline": "SERWER ONLINE (OCZEKIWANIE)",
      "CreateCustomLobby": "UTWÓRZ WŁASNE LOBBY",
      "CancelSearch": "ANULUJ",
      "Score": "Wynik",
      "Warmup": "ROZGRZEWKA",
      "HalfTime": "PRZERWA",
      "Final": "KONIEC",
      "MatchEndedMining": "Mecz zakończony. Kopanie bloku...",
      "Lobby": "LOBBY",
      "TeamRoster": "SKŁAD DRUŻYNY",
      "VS": "VS",
      "EmptySlot": "Puste miejsce",
      "ConfigError": "BŁĄD KONFIGURACJI",
      "ConfigWriteError": "Nie można zapisać konfiguracji GSI.",
      "ACRequired": "WYMAGANY ANTY-CHEAT",
      "ShieldRequiredMsg": "Aktywna tarcza wymagana do hostowania.",
      "EnableShieldMsg": "Musisz włączyć Eden Anti-Cheat.",
      "InsufficientFunds": "NIEWYSTARCZAJĄCE ŚRODKI",
      "TransactionFailed": "TRANSAKCJA NIEUDANA",
      "ProcessDeductionFailed": "Nie można przetworzyć potrącenia.",
      "Error": "Błąd",
      "OK": "OK",
      "Cancel": "ANULUJ",
      "Close": "ZAMKNIJ",
      "Loading": "ŁADOWANIE",
      "FriendsList": "LISTA ZNAJOMYCH",
      "AddFriend": "DODAJ ZNAJOMEGO",
      "EnterFriendCode": "Wprowadź kod znajomego / Peer ID",
      "NoFriendsMsg": "Brak znajomych. Dodaj kogoś przez Peer ID.",
      "Invite": "ZAPROŚ",
      "InvitedMsg": "Zaproszono do lobby",
      "Trade": "HANDEL",
      "FriendCode": "KOD ZNAJOMEGO",
      "PeerID": "PEER ID",
      "Level": "POZIOM",
      "Skill": "Umiejętności",
      "IncomingRequest": "Otrzymane zaproszenie",
      "RequestSent": "Wysłano zaproszenie...",
      "Pending": "OCZEKIWANIE",
      "Offline": "Offline",
      "ChangeIdentity": "ZMIEŃ TOŻSAMOŚĆ",
      "ChangeIdentityCost": "Zmiana aliasu kosztuje 10 EDN.",
      "NewAlias": "Nowy alias",
      "Pay10EDN": "ZAPŁAĆ 10 EDN",
      "EdenWallet": "PORTFEL EDEN",
      "LiveBalance": "Bieżące saldo",
      "Send": "WYŚLIJ",
      "Receive": "ODBIERZ",
      "SendEDN": "WYŚLIJ EDN",
      "ReceiveEDN": "ODBIERZ EDN",
      "ReceiverID": "Peer ID odbiorcy",
      "Amount": "Kwota",
      "ShareIDMsg": "Udostępnij to ID, aby otrzymać środki:",
      "Copy": "KOPIUJ",
      "MiningRewardsMsg": "Nagrody za kopanie są przyznawane po każdym meczu.",
      "TransferFailed": "Przelew nieudany.",
      "CopiedClipboard": "Skopiowano do schowka",
      "SecureTradeOffer": "BEZPIECZNA OFERTA HANDLOWA",
      "Holdings": "Posiadane",
      "EstRemaining": "Szac. pozostałe:",
      "EstTotal": "Szac. łącznie:",
      "TradingAmount": "KWOTA HANDLU",
      "CancelTrade": "ANULUJ HANDEL",
      "ConfirmAccept": "POTWIERDŹ I AKCEPTUJ",
      "TradeSuccessful": "Handel udany!",
      "TradeFailed": "Handel nieudany.",
      "AuctionTab": "AUKCJA",
      "BetTab": "ZAKŁADY",
      "SyncwithBlockchain": "Synchronizacja z Blockchain",
      "GlobalMarket": "RYNEK GLOBALNY",
      "SellItemBtn": "SPRZEDAJ PRZEDMIOT",
      "NoListingsMsg": "Brak aktywnych ofert w łańcuchu.",
      "NoLiveMatches": "Brak meczów na żywo.",
      "BroadcastMsg": "Serwery nadają automatycznie podczas gry.",
      "LiveTag": "NA ŻYWO",
      "YouTag": "TY",
      "ListedBtn": "WYSTAWIONO",
      "BuyNowBtn": "KUP TERAZ",
      "SelectItemToSell": "Wybierz przedmiot na sprzedaż",
      "ListItemBtn": "WYSTAW PRZEDMIOT",
      "Price": "Cena",
      "Duration": "Czas trwania (sek)",
      "BetPlaced": "Zakład przyjęty!",
      "BetFailed": "Zakład nieudany",
      "MatchHistory": "HISTORIA MECZÓW",
      "AnalyzeDemoBtn": "ANALIZUJ NOWE DEMO",
      "SelectMatchTitle": "WYBIERZ MECZ",
      "SelectMatchMsg": "Wybierz mecz z lewej, aby zobaczyć szczegóły",
      "Scoreboard": "TABELA WYNIKÓW",
      "DownloadDemo": "POBIERZ DEMO",
      "WatchRoom": "OGLĄDAJ POKÓJ",
      "HeaderPlayer": "GRACZ",
      "HeaderKills": "ZABÓJSTWA",
      "HeaderDeaths": "ŚMIERCI",
      "HeaderKD": "K/D",
      "HeaderADR": "ADR",
      "HeaderRating": "OCENA",
      "MatchAnalyzed": "MECZ PRZEANALIZOWANY",
      "AnalysisFailed": "Analiza nieudana",
      "Settings": "USTAWIENIA",
      "CS2Path": "Ścieżka instalacji CS2",
      "CSGOPath": "Ścieżka instalacji CSGO",
      "Steam64ID": "Steam 64 ID (Do handlu)",
      "SteamAPIKey": "Klucz API Steam",
      "DBUser": "Użytkownik bazy danych",
      "DBPassword": "Hasło bazy danych",
      "LanguageLabel": "Język",
      "Save": "ZAPISZ",
      "Submit": "ZATWIERDŹ",
      "SettingsSavedMsg": "Ustawienia zapisane. Zrestartuj aplikację.",
      "MapSelection": "WYBÓR MAPY",
      "PasteHubID": "MatchID@HostPeerID",
      "Map": "Mapa",
      "Connect": "POŁĄCZ",
    },

    // --- Japanese ---
    "Japanese": {
      "AppTitle": "EDENクライアント",
      "PlayTitle": "プレイ",
      "SocialTitle": "ソーシャル",
      "ProConfigTitle": "プロ設定",
      "MarketplaceTitle": "マーケットプレイス",
      "Play": "プレイ",
      "Matchmaking": "マッチメイキング",
      "Tournaments": "トーナメント",
      "Deathmatch": "デスマッチ",
      "1v1Hubs": "1v1ハブ",
      "Status": "ステータス",
      "Idle": "待機中",
      "WaitingAction": "アクション待ち",
      "InitializingAC": "アンチチート初期化中...",
      "ACActive": "アンチチート有効",
      "EdenACActive": "EDEN AC稼働中",
      "TunnelSecured": "保護",
      "TunnelWaiting": "待機中",
      "SessionConnected": "接続済み",
      "SessionIdle": "アイドル",
      "AntiCheat": "アンチチート",
      "StartMatching": "マッチング開始",
      "CancelMatching": "マッチングキャンセル",
      "Searching": "検索中",
      "SearchingMsg": "マッチを検索中...",
      "MatchFound": "マッチが見つかりました！",
      "MatchCancelled": "マッチがキャンセルされました",
      "StopServer": "サーバー停止",
      "StartingServer": "サーバー起動中",
      "ServerOnline": "サーバーオンライン (待機中)",
      "CreateCustomLobby": "カスタムロビー作成",
      "CancelSearch": "キャンセル",
      "Score": "スコア",
      "Warmup": "ウォームアップ",
      "HalfTime": "ハーフタイム",
      "Final": "終了",
      "MatchEndedMining": "試合終了。ブロック採掘中...",
      "Lobby": "ロビー",
      "TeamRoster": "チーム名簿",
      "VS": "VS",
      "EmptySlot": "空きスロット",
      "ConfigError": "設定エラー",
      "ConfigWriteError": "GSI設定を書き込めませんでした。",
      "ACRequired": "アンチチート必須",
      "ShieldRequiredMsg": "ホストするにはシールドを有効にしてください。",
      "EnableShieldMsg": "Edenアンチチートシールドを有効にする必要があります。",
      "InsufficientFunds": "残高不足",
      "TransactionFailed": "取引失敗",
      "ProcessDeductionFailed": "引き落とし処理に失敗しました。",
      "Error": "エラー",
      "OK": "OK",
      "Cancel": "キャンセル",
      "Close": "閉じる",
      "Loading": "読み込み中",
      "FriendsList": "フレンドリスト",
      "AddFriend": "フレンド追加",
      "EnterFriendCode": "フレンドコード / Peer ID",
      "NoFriendsMsg": "フレンドがいません。IDで追加してください。",
      "Invite": "招待",
      "InvitedMsg": "ロビーに招待しました",
      "Trade": "トレード",
      "FriendCode": "フレンドコード",
      "PeerID": "PEER ID",
      "Level": "レベル",
      "Skill": "スキル",
      "IncomingRequest": "フレンド申請が届いています",
      "RequestSent": "申請送信済み - 待機中...",
      "Pending": "保留中",
      "Offline": "オフライン",
      "ChangeIdentity": "ID変更",
      "ChangeIdentityCost": "エイリアス変更には10 EDNかかります。",
      "NewAlias": "新しいエイリアス",
      "Pay10EDN": "10 EDN支払う",
      "EdenWallet": "EDENウォレット",
      "LiveBalance": "現在残高",
      "Send": "送る",
      "Receive": "受け取る",
      "SendEDN": "EDNを送る",
      "ReceiveEDN": "EDNを受け取る",
      "ReceiverID": "受取人のPeer ID",
      "Amount": "数量",
      "ShareIDMsg": "資金を受け取るにはこのIDを共有してください:",
      "Copy": "コピー",
      "MiningRewardsMsg": "マイニング報酬は試合終了後に付与されます。",
      "TransferFailed": "送金失敗",
      "CopiedClipboard": "クリップボードにコピーしました",
      "SecureTradeOffer": "安全なトレード提案",
      "Holdings": "保有額",
      "EstRemaining": "推定残り:",
      "EstTotal": "推定合計:",
      "TradingAmount": "トレード額",
      "CancelTrade": "トレードキャンセル",
      "ConfirmAccept": "確認して承諾",
      "TradeSuccessful": "トレード成功！",
      "TradeFailed": "トレード失敗",
      "AuctionTab": "オークション",
      "BetTab": "ベット",
      "SyncwithBlockchain": "ブロックチェーンと同期",
      "GlobalMarket": "グローバルマーケット",
      "SellItemBtn": "アイテムを出品",
      "NoListingsMsg": "チェーン上にアクティブなリストはありません。",
      "NoLiveMatches": "ライブマッチはありません。",
      "BroadcastMsg": "サーバーはライブ時に自動的にブロードキャストします。",
      "LiveTag": "ライブ",
      "YouTag": "あなた",
      "ListedBtn": "出品中",
      "BuyNowBtn": "今すぐ購入",
      "SelectItemToSell": "出品するアイテムを選択",
      "ListItemBtn": "アイテムを出品",
      "Price": "価格",
      "Duration": "期間 (秒)",
      "BetPlaced": "ベット完了！",
      "BetFailed": "ベット失敗",
      "MatchHistory": "対戦履歴",
      "AnalyzeDemoBtn": "新しいデモを分析",
      "SelectMatchTitle": "マッチを選択",
      "SelectMatchMsg": "左側からマッチを選択して詳細分析を表示",
      "Scoreboard": "スコアボード",
      "DownloadDemo": "デモをダウンロード",
      "WatchRoom": "観戦ルーム",
      "HeaderPlayer": "プレイヤー",
      "HeaderKills": "キル",
      "HeaderDeaths": "デス",
      "HeaderKD": "K/D",
      "HeaderADR": "ADR",
      "HeaderRating": "レーティング",
      "MatchAnalyzed": "マッチ分析完了",
      "AnalysisFailed": "分析失敗",
      "Settings": "設定",
      "CS2Path": "CS2インストールパス",
      "CSGOPath": "CSGOインストールパス",
      "Steam64ID": "Steam 64 ID (トレード用)",
      "SteamAPIKey": "Steam Web APIキー",
      "DBUser": "DBユーザー",
      "DBPassword": "DBパスワード",
      "LanguageLabel": "言語",
      "Save": "保存",
      "Submit": "送信",
      "SettingsSavedMsg": "設定を保存しました。アプリを再起動してください。",
      "MapSelection": "マップ選択",
      "PasteHubID": "MatchID@HostPeerID",
      "Map": "マップ",
      "Connect": "接続",
    },

    // --- Korean ---
    "Korean": {
      "AppTitle": "EDEN 클라이언트",
      "PlayTitle": "플레이",
      "SocialTitle": "소셜",
      "ProConfigTitle": "프로 설정",
      "MarketplaceTitle": "마켓플레이스",
      "Play": "플레이",
      "Matchmaking": "매치메이킹",
      "Tournaments": "토너먼트",
      "Deathmatch": "데스매치",
      "1v1Hubs": "1v1 허브",
      "Status": "상태",
      "Idle": "대기",
      "WaitingAction": "작업 대기 중",
      "InitializingAC": "안티치트 초기화 중...",
      "ACActive": "안티치트 활성화",
      "EdenACActive": "EDEN AC 작동 중",
      "TunnelSecured": "보안됨",
      "TunnelWaiting": "대기 중",
      "SessionConnected": "연결됨",
      "SessionIdle": "유휴",
      "AntiCheat": "안티치트",
      "StartMatching": "매칭 시작",
      "CancelMatching": "매칭 취소",
      "Searching": "검색 중",
      "SearchingMsg": "매치 검색 중...",
      "MatchFound": "매치 찾음!",
      "MatchCancelled": "매치 취소됨",
      "StopServer": "서버 중지",
      "StartingServer": "서버 시작 중",
      "ServerOnline": "서버 온라인 (대기 중)",
      "CreateCustomLobby": "커스텀 로비 생성",
      "CancelSearch": "검색 취소",
      "Score": "점수",
      "Warmup": "웜업",
      "HalfTime": "하프타임",
      "Final": "종료",
      "MatchEndedMining": "매치 종료. 블록 채굴 중...",
      "Lobby": "로비",
      "TeamRoster": "팀 명단",
      "VS": "VS",
      "EmptySlot": "빈 슬롯",
      "ConfigError": "설정 오류",
      "ConfigWriteError": "GSI 설정을 쓸 수 없습니다.",
      "ACRequired": "안티치트 필요",
      "ShieldRequiredMsg": "호스팅하려면 쉴드를 활성화해야 합니다.",
      "EnableShieldMsg": "Eden 안티치트 쉴드를 활성화해야 합니다.",
      "InsufficientFunds": "잔액 부족",
      "TransactionFailed": "거래 실패",
      "ProcessDeductionFailed": "차감 처리에 실패했습니다.",
      "Error": "오류",
      "OK": "확인",
      "Cancel": "취소",
      "Close": "닫기",
      "Loading": "로딩 중",
      "FriendsList": "친구 목록",
      "AddFriend": "친구 추가",
      "EnterFriendCode": "친구 코드 / Peer ID 입력",
      "NoFriendsMsg": "친구가 없습니다. ID를 사용하여 추가하세요.",
      "Invite": "초대",
      "InvitedMsg": "로비로 초대됨",
      "Trade": "거래",
      "FriendCode": "친구 코드",
      "PeerID": "PEER ID",
      "Level": "레벨",
      "Skill": "스킬",
      "IncomingRequest": "친구 요청 수신",
      "RequestSent": "요청 보냄 - 대기 중...",
      "Pending": "보류 중",
      "Offline": "오프라인",
      "ChangeIdentity": "신원 변경",
      "ChangeIdentityCost": "별칭 변경 비용은 10 EDN입니다.",
      "NewAlias": "새 별칭",
      "Pay10EDN": "10 EDN 지불",
      "EdenWallet": "EDEN 지갑",
      "LiveBalance": "실시간 잔액",
      "Send": "보내기",
      "Receive": "받기",
      "SendEDN": "EDN 보내기",
      "ReceiveEDN": "EDN 받기",
      "ReceiverID": "수신자 Peer ID",
      "Amount": "수량",
      "ShareIDMsg": "자금을 받으려면 이 ID를 공유하세요:",
      "Copy": "복사",
      "MiningRewardsMsg": "채굴 보상은 매치 후 지급됩니다.",
      "TransferFailed": "이체 실패.",
      "CopiedClipboard": "클립보드에 복사됨",
      "SecureTradeOffer": "안전 거래 제안",
      "Holdings": "보유량",
      "EstRemaining": "예상 잔액:",
      "EstTotal": "예상 합계:",
      "TradingAmount": "거래 금액",
      "CancelTrade": "거래 취소",
      "ConfirmAccept": "확인 및 수락",
      "TradeSuccessful": "거래 성공!",
      "TradeFailed": "거래 실패.",
      "AuctionTab": "경매",
      "BetTab": "베팅",
      "SyncwithBlockchain": "블록체인과 동기화",
      "GlobalMarket": "글로벌 마켓",
      "SellItemBtn": "아이템 판매",
      "NoListingsMsg": "체인에 활성 목록이 없습니다.",
      "NoLiveMatches": "라이브 매치가 없습니다.",
      "BroadcastMsg": "서버는 라이브 시 자동으로 방송합니다.",
      "LiveTag": "라이브",
      "YouTag": "나",
      "ListedBtn": "등록됨",
      "BuyNowBtn": "즉시 구매",
      "SelectItemToSell": "판매할 아이템 선택",
      "ListItemBtn": "아이템 등록",
      "Price": "가격",
      "Duration": "기간 (초)",
      "BetPlaced": "베팅 완료!",
      "BetFailed": "베팅 실패",
      "MatchHistory": "매치 기록",
      "AnalyzeDemoBtn": "새 데모 분석",
      "SelectMatchTitle": "매치 선택",
      "SelectMatchMsg": "왼쪽에서 매치를 선택하여 상세 분석 보기",
      "Scoreboard": "점수판",
      "DownloadDemo": "데모 다운로드",
      "WatchRoom": "관전방",
      "HeaderPlayer": "플레이어",
      "HeaderKills": "킬",
      "HeaderDeaths": "데스",
      "HeaderKD": "K/D",
      "HeaderADR": "ADR",
      "HeaderRating": "평점",
      "MatchAnalyzed": "매치 분석됨",
      "AnalysisFailed": "분석 실패",
      "Settings": "설정",
      "CS2Path": "CS2 설치 경로",
      "CSGOPath": "CSGO 설치 경로",
      "Steam64ID": "Steam 64 ID (거래용)",
      "SteamAPIKey": "Steam Web API 키",
      "DBUser": "DB 사용자",
      "DBPassword": "DB 비밀번호",
      "LanguageLabel": "언어",
      "Save": "저장",
      "Submit": "제출",
      "SettingsSavedMsg": "설정 저장됨. 앱을 재시작하세요.",
      "MapSelection": "지도 선택",
      "PasteHubID": "MatchID@HostPeerID",
      "Map": "지도",
      "Connect": "연결",
    },

    // --- French ---
    "French": {
      "AppTitle": "Client EDEN",
      "PlayTitle": "JOUER",
      "SocialTitle": "Social",
      "ProConfigTitle": "Config PRO",
      "MarketplaceTitle": "MARCHÉ",
      "Play": "JOUER",
      "Matchmaking": "MATCHMAKING",
      "Tournaments": "TOURNOIS",
      "Deathmatch": "DEATHMATCH",
      "1v1Hubs": "HUBS 1V1",
      "Status": "Statut",
      "Idle": "Inactif",
      "WaitingAction": "EN ATTENTE",
      "InitializingAC": "INITIALISATION AC...",
      "ACActive": "ANTI-CHEAT ACTIF",
      "EdenACActive": "EDEN AC ACTIF",
      "TunnelSecured": "SÉCURISÉ",
      "TunnelWaiting": "EN ATTENTE",
      "SessionConnected": "CONNECTÉ",
      "SessionIdle": "INACTIF",
      "AntiCheat": "ANTI-CHEAT",
      "StartMatching": "LANCER RECHERCHE",
      "CancelMatching": "ANNULER RECHERCHE",
      "Searching": "RECHERCHE",
      "SearchingMsg": "RECHERCHE DE MATCH...",
      "MatchFound": "MATCH TROUVÉ !",
      "MatchCancelled": "MATCH ANNULÉ",
      "StopServer": "ARRÊTER SERVEUR",
      "StartingServer": "DÉMARRAGE SERVEUR",
      "ServerOnline": "SERVEUR EN LIGNE (ATTENTE)",
      "CreateCustomLobby": "CRÉER LOBBY PERSO",
      "CancelSearch": "ANNULER",
      "Score": "Score",
      "Warmup": "ÉCHAUFFEMENT",
      "HalfTime": "MI-TEMPS",
      "Final": "FINAL",
      "MatchEndedMining": "Match terminé. Minage du bloc...",
      "Lobby": "LOBBY",
      "TeamRoster": "ÉQUIPE",
      "VS": "VS",
      "EmptySlot": "Place vide",
      "ConfigError": "ERREUR CONFIG",
      "ConfigWriteError": "Impossible d'écrire la config GSI.",
      "ACRequired": "ANTI-CHEAT REQUIS",
      "ShieldRequiredMsg": "Le bouclier est requis pour héberger.",
      "EnableShieldMsg": "Vous devez activer le bouclier Eden.",
      "InsufficientFunds": "FONDS INSUFFISANTS",
      "TransactionFailed": "TRANSACTION ÉCHOUÉE",
      "ProcessDeductionFailed": "Impossible de traiter la déduction.",
      "Error": "Erreur",
      "OK": "OK",
      "Cancel": "ANNULER",
      "Close": "FERMER",
      "Loading": "CHARGEMENT",
      "FriendsList": "AMIS",
      "AddFriend": "AJOUTER AMI",
      "EnterFriendCode": "Entrer code ami / Peer ID",
      "NoFriendsMsg": "Pas d'amis. Ajoutez-en via Peer ID.",
      "Invite": "INVITER",
      "InvitedMsg": "Invité au lobby",
      "Trade": "ÉCHANGE",
      "FriendCode": "CODE AMI",
      "PeerID": "PEER ID",
      "Level": "NIVEAU",
      "Skill": "Compétence",
      "IncomingRequest": "Demande reçue",
      "RequestSent": "Demande envoyée...",
      "Pending": "EN ATTENTE",
      "Offline": "Hors ligne",
      "ChangeIdentity": "CHANGER IDENTITÉ",
      "ChangeIdentityCost": "Changer d'alias coûte 10 EDN.",
      "NewAlias": "Nouvel alias",
      "Pay10EDN": "PAYER 10 EDN",
      "EdenWallet": "PORTEFEUILLE EDEN",
      "LiveBalance": "Solde en direct",
      "Send": "ENVOYER",
      "Receive": "RECEVOIR",
      "SendEDN": "ENVOYER EDN",
      "ReceiveEDN": "RECEVOIR EDN",
      "ReceiverID": "Peer ID destinataire",
      "Amount": "Montant",
      "ShareIDMsg": "Partagez cet ID pour recevoir des fonds :",
      "Copy": "COPIER",
      "MiningRewardsMsg": "Récompenses de minage après chaque match.",
      "TransferFailed": "Transfert échoué.",
      "CopiedClipboard": "Copié dans le presse-papier",
      "SecureTradeOffer": "OFFRE D'ÉCHANGE SÉCURISÉE",
      "Holdings": "Avoirs",
      "EstRemaining": "Est. Restant :",
      "EstTotal": "Est. Total :",
      "TradingAmount": "MONTANT ÉCHANGE",
      "CancelTrade": "ANNULER",
      "ConfirmAccept": "ACCEPTER",
      "TradeSuccessful": "Échange réussi !",
      "TradeFailed": "Échange échoué.",
      "AuctionTab": "ENCHÈRES",
      "BetTab": "PARIS",
      "SyncwithBlockchain": "Synchronisation avec blockchain",
      "GlobalMarket": "MARCHÉ MONDIAL",
      "SellItemBtn": "VENDRE OBJET",
      "NoListingsMsg": "Aucune annonce active sur la chaîne.",
      "NoLiveMatches": "Aucun match en direct.",
      "BroadcastMsg": "Les serveurs diffusent automatiquement.",
      "LiveTag": "EN DIRECT",
      "YouTag": "VOUS",
      "ListedBtn": "LISTÉ",
      "BuyNowBtn": "ACHETER",
      "SelectItemToSell": "Sélectionner objet à vendre",
      "ListItemBtn": "LISTER OBJET",
      "Price": "Prix",
      "Duration": "Durée (sec)",
      "BetPlaced": "Pari placé !",
      "BetFailed": "Pari échoué",
      "MatchHistory": "HISTORIQUE MATCHS",
      "AnalyzeDemoBtn": "ANALYSER NOUVELLE DÉMO",
      "SelectMatchTitle": "SÉLECTIONNER MATCH",
      "SelectMatchMsg": "Sélectionnez un match à gauche pour voir les détails",
      "Scoreboard": "TABLEAU DES SCORES",
      "DownloadDemo": "TÉLÉCHARGER DÉMO",
      "WatchRoom": "REGARDER",
      "HeaderPlayer": "JOUEUR",
      "HeaderKills": "KILLS",
      "HeaderDeaths": "MORTS",
      "HeaderKD": "K/D",
      "HeaderADR": "ADR",
      "HeaderRating": "RATING",
      "MatchAnalyzed": "MATCH ANALYSÉ",
      "AnalysisFailed": "Analyse échouée",
      "Settings": "PARAMÈTRES",
      "CS2Path": "Chemin installation CS2",
      "CSGOPath": "Chemin installation CSGO",
      "Steam64ID": "Steam 64 ID (Pour échange)",
      "SteamAPIKey": "Clé API Web Steam",
      "DBUser": "Utilisateur BDD",
      "DBPassword": "Mot de passe BDD",
      "LanguageLabel": "Langue",
      "Save": "SAUVEGARDER",
      "Submit": "SOUMETTRE",
      "SettingsSavedMsg": "Paramètres sauvegardés. Redémarrez l'app.",
      "MapSelection": "SÉLECTION CARTE",
      "PasteHubID": "MatchID@HostPeerID",
      "Map": "Carte",
      "Connect": "CONNECTER",
    },

    // --- German ---
    "German": {
      "AppTitle": "EDEN Client",
      "PlayTitle": "SPIELEN",
      "SocialTitle": "Sozial",
      "ProConfigTitle": "PRO Konfig",
      "MarketplaceTitle": "MARKTPLATZ",
      "Play": "SPIELEN",
      "Matchmaking": "MATCHMAKING",
      "Tournaments": "TURNIERE",
      "Deathmatch": "DEATHMATCH",
      "1v1Hubs": "1V1 HUBS",
      "Status": "Status",
      "Idle": "Leerlauf",
      "WaitingAction": "WARTE AUF AKTION",
      "InitializingAC": "INITIALISIERE AC...",
      "ACActive": "ANTI-CHEAT AKTIV",
      "EdenACActive": "EDEN AC LÄUFT",
      "TunnelSecured": "GESICHERT",
      "TunnelWaiting": "WARTEN",
      "SessionConnected": "VERBUNDEN",
      "SessionIdle": "LEERLAUF",
      "AntiCheat": "ANTI-CHEAT",
      "StartMatching": "SUCHE STARTEN",
      "CancelMatching": "SUCHE ABBRECHEN",
      "Searching": "SUCHEN",
      "SearchingMsg": "SUCHE MATCH...",
      "MatchFound": "MATCH GEFUNDEN!",
      "MatchCancelled": "MATCH ABGEBROCHEN",
      "StopServer": "SERVER STOPPEN",
      "StartingServer": "STARTE SERVER",
      "ServerOnline": "SERVER ONLINE (WARTEN)",
      "CreateCustomLobby": "LOBBY ERSTELLEN",
      "CancelSearch": "ABBRECHEN",
      "Score": "Ergebnis",
      "Warmup": "AUFWÄRMEN",
      "HalfTime": "HALBZEIT",
      "Final": "ENDE",
      "MatchEndedMining": "Spiel beendet. Mining Block...",
      "Lobby": "LOBBY",
      "TeamRoster": "TEAM-ROSTER",
      "VS": "VS",
      "EmptySlot": "Leerer Slot",
      "ConfigError": "KONFIG FEHLER",
      "ConfigWriteError": "Konnte GSI-Konfig nicht schreiben.",
      "ACRequired": "ANTI-CHEAT ERFORDERLICH",
      "ShieldRequiredMsg": "Aktiver Schutz zum Hosten erforderlich.",
      "EnableShieldMsg": "Sie müssen den Eden Anti-Cheat aktivieren.",
      "InsufficientFunds": "NICHT GENÜGEND GUTHABEN",
      "TransactionFailed": "TRANSAKTION FEHLGESCHLAGEN",
      "ProcessDeductionFailed": "Abbuchung konnte nicht verarbeitet werden.",
      "Error": "Fehler",
      "OK": "OK",
      "Cancel": "ABBRECHEN",
      "Close": "SCHLIESSEN",
      "Loading": "LADEN",
      "FriendsList": "FREUNDESLISTE",
      "AddFriend": "FREUND HINZUFÜGEN",
      "EnterFriendCode": "Freundescode / Peer ID eingeben",
      "NoFriendsMsg": "Keine Freunde. Füge jemanden per ID hinzu.",
      "Invite": "EINLADEN",
      "InvitedMsg": "In Lobby eingeladen",
      "Trade": "HANDELN",
      "FriendCode": "FREUNDESCODE",
      "PeerID": "PEER ID",
      "Level": "LEVEL",
      "Skill": "Skill",
      "IncomingRequest": "Eingehende Anfrage",
      "RequestSent": "Anfrage gesendet...",
      "Pending": "AUSSTEHEND",
      "Offline": "Offline",
      "ChangeIdentity": "IDENTITÄT ÄNDERN",
      "ChangeIdentityCost": "Namensänderung kostet 10 EDN.",
      "NewAlias": "Neuer Alias",
      "Pay10EDN": "10 EDN ZAHLEN",
      "EdenWallet": "EDEN WALLET",
      "LiveBalance": "Live-Guthaben",
      "Send": "SENDEN",
      "Receive": "EMPFANGEN",
      "SendEDN": "EDN SENDEN",
      "ReceiveEDN": "EDN EMPFANGEN",
      "ReceiverID": "Empfänger Peer ID",
      "Amount": "Betrag",
      "ShareIDMsg": "Teile diese ID um Geld zu empfangen:",
      "Copy": "KOPIEREN",
      "MiningRewardsMsg": "Mining-Belohnungen werden nach dem Match gutgeschrieben.",
      "TransferFailed": "Transfer fehlgeschlagen.",
      "CopiedClipboard": "In Zwischenablage kopiert",
      "SecureTradeOffer": "SICHERES HANDELSANGEBOT",
      "Holdings": "Bestand",
      "EstRemaining": "Gesch. Verbleibend:",
      "EstTotal": "Gesch. Gesamt:",
      "TradingAmount": "HANDELSBETRAG",
      "CancelTrade": "HANDEL ABBRECHEN",
      "ConfirmAccept": "BESTÄTIGEN & AKZEPTIEREN",
      "TradeSuccessful": "Handel erfolgreich!",
      "TradeFailed": "Handel fehlgeschlagen.",
      "AuctionTab": "AUKTION",
      "BetTab": "WETTEN",
      "SyncwithBlockchain": "Synchronisieren mit Blockchain",
      "GlobalMarket": "GLOBALER MARKT",
      "SellItemBtn": "ITEM VERKAUFEN",
      "NoListingsMsg": "Keine aktiven Angebote auf der Chain.",
      "NoLiveMatches": "Keine Live-Matches.",
      "BroadcastMsg": "Server übertragen automatisch, wenn live.",
      "LiveTag": "LIVE",
      "YouTag": "DU",
      "ListedBtn": "GELISTET",
      "BuyNowBtn": "JETZT KAUFEN",
      "SelectItemToSell": "Item zum Verkauf wählen",
      "ListItemBtn": "ITEM LISTEN",
      "Price": "Preis",
      "Duration": "Dauer (Sek)",
      "BetPlaced": "Wette platziert!",
      "BetFailed": "Wette fehlgeschlagen",
      "MatchHistory": "MATCH-HISTORIE",
      "AnalyzeDemoBtn": "NEUE DEMO ANALYSIEREN",
      "SelectMatchTitle": "MATCH WÄHLEN",
      "SelectMatchMsg": "Wähle ein Match links für Details",
      "Scoreboard": "SCOREBOARD",
      "DownloadDemo": "DEMO HERUNTERLADEN",
      "WatchRoom": "RAUM ANSEHEN",
      "HeaderPlayer": "SPIELER",
      "HeaderKills": "KILLS",
      "HeaderDeaths": "DEATHS",
      "HeaderKD": "K/D",
      "HeaderADR": "ADR",
      "HeaderRating": "RATING",
      "MatchAnalyzed": "MATCH ANALYSIERT",
      "AnalysisFailed": "Analyse fehlgeschlagen",
      "Settings": "EINSTELLUNGEN",
      "CS2Path": "CS2 Installationspfad",
      "CSGOPath": "CSGO Installationspfad",
      "Steam64ID": "Steam 64 ID (Für Handel)",
      "SteamAPIKey": "Steam Web API Key",
      "DBUser": "DB Benutzer",
      "DBPassword": "DB Passwort",
      "LanguageLabel": "Sprache",
      "Save": "SPEICHERN",
      "Submit": "ABSENDEN",
      "SettingsSavedMsg": "Einstellungen gespeichert. App neu starten.",
      "MapSelection": "KARTENAUSWAHL",
      "PasteHubID": "MatchID@HostPeerID",
      "Map": "Karte",
      "Connect": "VERBINDEN",
    },

    // --- Spanish ---
    "Spanish": {
      "AppTitle": "Cliente EDEN",
      "PlayTitle": "JUGAR",
      "SocialTitle": "Social",
      "ProConfigTitle": "Config PRO",
      "MarketplaceTitle": "MERCADO",
      "Play": "JUGAR",
      "Matchmaking": "MATCHMAKING",
      "Tournaments": "TORNEOS",
      "Deathmatch": "DEATHMATCH",
      "1v1Hubs": "HUBS 1V1",
      "Status": "Estado",
      "Idle": "Inactivo",
      "WaitingAction": "ESPERANDO ACCIÓN",
      "InitializingAC": "INICIANDO AC...",
      "ACActive": "ANTI-CHEAT ACTIVO",
      "EdenACActive": "EDEN AC ACTIVO",
      "TunnelSecured": "SEGURO",
      "TunnelWaiting": "ESPERANDO",
      "SessionConnected": "CONECTADO",
      "SessionIdle": "INACTIVO",
      "AntiCheat": "ANTI-CHEAT",
      "StartMatching": "BUSCAR PARTIDA",
      "CancelMatching": "CANCELAR BÚSQUEDA",
      "Searching": "BUSCANDO",
      "SearchingMsg": "BUSCANDO PARTIDA...",
      "MatchFound": "¡PARTIDA ENCONTRADA!",
      "MatchCancelled": "PARTIDA CANCELADA",
      "StopServer": "DETENER SERVIDOR",
      "StartingServer": "INICIANDO SERVIDOR",
      "ServerOnline": "SERVIDOR ONLINE (ESPERANDO)",
      "CreateCustomLobby": "CREAR LOBBY PERSONALIZADO",
      "CancelSearch": "CANCELAR",
      "Score": "Puntuación",
      "Warmup": "CALENTAMIENTO",
      "HalfTime": "MEDIO TIEMPO",
      "Final": "FINAL",
      "MatchEndedMining": "Partida terminada. Minando bloque...",
      "Lobby": "LOBBY",
      "TeamRoster": "EQUIPO",
      "VS": "VS",
      "EmptySlot": "Hueco libre",
      "ConfigError": "ERROR DE CONFIG",
      "ConfigWriteError": "No se pudo escribir la config GSI.",
      "ACRequired": "ANTI-CHEAT REQUERIDO",
      "ShieldRequiredMsg": "Se requiere escudo activo para alojar.",
      "EnableShieldMsg": "Debes habilitar el escudo Eden Anti-Cheat.",
      "InsufficientFunds": "FONDOS INSUFICIENTES",
      "TransactionFailed": "TRANSACCIÓN FALLIDA",
      "ProcessDeductionFailed": "No se pudo procesar la deducción.",
      "Error": "Error",
      "OK": "OK",
      "Cancel": "CANCELAR",
      "Close": "CERRAR",
      "Loading": "CARGANDO",
      "FriendsList": "LISTA DE AMIGOS",
      "AddFriend": "AÑADIR AMIGO",
      "EnterFriendCode": "Introducir código amigo / Peer ID",
      "NoFriendsMsg": "Sin amigos. Añade uno usando su Peer ID.",
      "Invite": "INVITAR",
      "InvitedMsg": "Invitado al lobby",
      "Trade": "INTERCAMBIAR",
      "FriendCode": "CÓDIGO AMIGO",
      "PeerID": "PEER ID",
      "Level": "NIVEL",
      "Skill": "Habilidad",
      "IncomingRequest": "Solicitud entrante",
      "RequestSent": "Solicitud enviada...",
      "Pending": "PENDIENTE",
      "Offline": "Desconectado",
      "ChangeIdentity": "CAMBIAR IDENTIDAD",
      "ChangeIdentityCost": "Cambiar tu alias cuesta 10 EDN.",
      "NewAlias": "Nuevo Alias",
      "Pay10EDN": "PAGAR 10 EDN",
      "EdenWallet": "CARTERA EDEN",
      "LiveBalance": "Saldo en vivo",
      "Send": "ENVIAR",
      "Receive": "RECIBIR",
      "SendEDN": "ENVIAR EDN",
      "ReceiveEDN": "RECIBIR EDN",
      "ReceiverID": "Peer ID del receptor",
      "Amount": "Cantidad",
      "ShareIDMsg": "Comparte este ID para recibir fondos:",
      "Copy": "COPIAR",
      "MiningRewardsMsg": "Las recompensas de minería se depositan tras cada partida.",
      "TransferFailed": "Transferencia fallida.",
      "CopiedClipboard": "Copiado al portapapeles",
      "SecureTradeOffer": "OFERTA DE INTERCAMBIO SEGURA",
      "Holdings": "Tenencias",
      "EstRemaining": "Est. Restante:",
      "EstTotal": "Est. Total:",
      "TradingAmount": "CANTIDAD A INTERCAMBIAR",
      "CancelTrade": "CANCELAR",
      "ConfirmAccept": "CONFIRMAR Y ACEPTAR",
      "TradeSuccessful": "¡Intercambio exitoso!",
      "TradeFailed": "Intercambio fallido.",
      "AuctionTab": "SUBASTA",
      "BetTab": "APUESTAS",
      "SyncwithBlockchain": "Sincronizar con la cadena de bloques",
      "GlobalMarket": "MERCADO GLOBAL",
      "SellItemBtn": "VENDER OBJETO",
      "NoListingsMsg": "No hay listados activos en la cadena.",
      "NoLiveMatches": "No hay partidas en vivo.",
      "BroadcastMsg": "Los servidores transmiten automáticamente cuando están en vivo.",
      "LiveTag": "EN VIVO",
      "YouTag": "TÚ",
      "ListedBtn": "LISTADO",
      "BuyNowBtn": "COMPRAR AHORA",
      "SelectItemToSell": "Seleccionar objeto para vender",
      "ListItemBtn": "LISTAR OBJETO",
      "Price": "Precio",
      "Duration": "Duración (seg)",
      "BetPlaced": "¡Apuesta realizada!",
      "BetFailed": "Apuesta fallida",
      "MatchHistory": "HISTORIAL DE PARTIDAS",
      "AnalyzeDemoBtn": "ANALIZAR NUEVA DEMO",
      "SelectMatchTitle": "SELECCIONAR PARTIDA",
      "SelectMatchMsg": "Selecciona una partida a la izquierda para ver análisis detallado",
      "Scoreboard": "MARCADOR",
      "DownloadDemo": "DESCARGAR DEMO",
      "WatchRoom": "VER SALA",
      "HeaderPlayer": "JUGADOR",
      "HeaderKills": "BAJAS",
      "HeaderDeaths": "MUERTES",
      "HeaderKD": "K/D",
      "HeaderADR": "ADR",
      "HeaderRating": "RATING",
      "MatchAnalyzed": "PARTIDA ANALIZADA",
      "AnalysisFailed": "Análisis fallido",
      "Settings": "AJUSTES",
      "CS2Path": "Ruta de instalación CS2",
      "CSGOPath": "Ruta de instalación CSGO",
      "Steam64ID": "Steam 64 ID (Para intercambio)",
      "SteamAPIKey": "Clave API Web Steam",
      "DBUser": "Usuario BD",
      "DBPassword": "Contraseña BD",
      "LanguageLabel": "Idioma",
      "Save": "GUARDAR",
      "Submit": "ENVIAR",
      "SettingsSavedMsg": "Ajustes guardados. Reinicia la app.",
      "MapSelection": "SELECCIÓN DE MAPA",
      "PasteHubID": "MatchID@HostPeerID",
      "Map": "Mapa",
      "Connect": "CONECTAR",
    },

    // --- Italian ---
    "Italian": {
      "AppTitle": "Client EDEN",
      "PlayTitle": "GIOCA",
      "SocialTitle": "Social",
      "ProConfigTitle": "Config PRO",
      "MarketplaceTitle": "MERCATO",
      "Play": "GIOCA",
      "Matchmaking": "MATCHMAKING",
      "Tournaments": "TORNEI",
      "Deathmatch": "DEATHMATCH",
      "1v1Hubs": "HUB 1V1",
      "Status": "Stato",
      "Idle": "Inattivo",
      "WaitingAction": "IN ATTESA DI AZIONE",
      "InitializingAC": "INIZIALIZZAZIONE AC...",
      "ACActive": "ANTI-CHEAT ATTIVO",
      "EdenACActive": "EDEN AC ATTIVO",
      "TunnelSecured": "SICURO",
      "TunnelWaiting": "IN ATTESA",
      "SessionConnected": "CONNESSO",
      "SessionIdle": "INATTIVO",
      "AntiCheat": "ANTI-CHEAT",
      "StartMatching": "INIZIA RICERCA",
      "CancelMatching": "ANNULLA RICERCA",
      "Searching": "RICERCA",
      "SearchingMsg": "RICERCA PARTITA...",
      "MatchFound": "PARTITA TROVATA!",
      "MatchCancelled": "PARTITA ANNULLATA",
      "StopServer": "FERMA SERVER",
      "StartingServer": "AVVIO SERVER",
      "ServerOnline": "SERVER ONLINE (ATTESA)",
      "CreateCustomLobby": "CREA LOBBY PERSONALIZZATA",
      "CancelSearch": "ANNULLA",
      "Score": "Punteggio",
      "Warmup": "RISCALDAMENTO",
      "HalfTime": "INTERVALLO",
      "Final": "FINALE",
      "MatchEndedMining": "Partita terminata. Mining del blocco...",
      "Lobby": "LOBBY",
      "TeamRoster": "ROSTER SQUADRA",
      "VS": "VS",
      "EmptySlot": "Slot vuoto",
      "ConfigError": "ERRORE CONFIG",
      "ConfigWriteError": "Impossibile scrivere config GSI.",
      "ACRequired": "ANTI-CHEAT RICHIESTO",
      "ShieldRequiredMsg": "Shield attivo richiesto per ospitare.",
      "EnableShieldMsg": "Devi abilitare Eden Anti-Cheat.",
      "InsufficientFunds": "FONDI INSUFFICIENTI",
      "TransactionFailed": "TRANSAZIONE FALLITA",
      "ProcessDeductionFailed": "Impossibile elaborare la deduzione.",
      "Error": "Errore",
      "OK": "OK",
      "Cancel": "ANNULLA",
      "Close": "CHIUDI",
      "Loading": "CARICAMENTO",
      "FriendsList": "LISTA AMICI",
      "AddFriend": "AGGIUNGI AMICO",
      "EnterFriendCode": "Inserisci codice amico / Peer ID",
      "NoFriendsMsg": "Nessun amico. Aggiungine uno tramite Peer ID.",
      "Invite": "INVITA",
      "InvitedMsg": "Invitato nella lobby",
      "Trade": "SCAMBIA",
      "FriendCode": "CODICE AMICO",
      "PeerID": "PEER ID",
      "Level": "LIVELLO",
      "Skill": "Abilità",
      "IncomingRequest": "Richiesta in arrivo",
      "RequestSent": "Richiesta inviata...",
      "Pending": "IN ATTESA",
      "Offline": "Offline",
      "ChangeIdentity": "CAMBIA IDENTITÀ",
      "ChangeIdentityCost": "Cambiare alias costa 10 EDN.",
      "NewAlias": "Nuovo Alias",
      "Pay10EDN": "PAGA 10 EDN",
      "EdenWallet": "PORTAFOGLIO EDEN",
      "LiveBalance": "Saldo in tempo reale",
      "Send": "INVIA",
      "Receive": "RICEVI",
      "SendEDN": "INVIA EDN",
      "ReceiveEDN": "RICEVI EDN",
      "ReceiverID": "Peer ID destinatario",
      "Amount": "Importo",
      "ShareIDMsg": "Condividi questo ID per ricevere fondi:",
      "Copy": "COPIA",
      "MiningRewardsMsg": "Le ricompense di mining vengono depositate dopo ogni partita.",
      "TransferFailed": "Trasferimento fallito.",
      "CopiedClipboard": "Copiato negli appunti",
      "SecureTradeOffer": "OFFERTA DI SCAMBIO SICURA",
      "Holdings": "Patrimonio",
      "EstRemaining": "Stima Rimanente:",
      "EstTotal": "Stima Totale:",
      "TradingAmount": "IMPORTO SCAMBIO",
      "CancelTrade": "ANNULLA",
      "ConfirmAccept": "CONFERMA E ACCETTA",
      "TradeSuccessful": "Scambio riuscito!",
      "TradeFailed": "Scambio fallito.",
      "AuctionTab": "ASTA",
      "BetTab": "SCOMMESSE",
      "SyncwithBlockchain": "Sincronizzazione con la blockchain",
      "GlobalMarket": "MERCATO GLOBALE",
      "SellItemBtn": "VENDI OGGETTO",
      "NoListingsMsg": "Nessuna inserzione attiva sulla catena.",
      "NoLiveMatches": "Nessuna partita in diretta.",
      "BroadcastMsg": "I server trasmettono automaticamente quando sono in diretta.",
      "LiveTag": "IN DIRETTA",
      "YouTag": "TU",
      "ListedBtn": "IN ELENCO",
      "BuyNowBtn": "COMPRA ORA",
      "SelectItemToSell": "Seleziona oggetto da vendere",
      "ListItemBtn": "ELENCA OGGETTO",
      "Price": "Prezzo",
      "Duration": "Durata (sec)",
      "BetPlaced": "Scommessa piazzata!",
      "BetFailed": "Scommessa fallita",
      "MatchHistory": "STORICO PARTITE",
      "AnalyzeDemoBtn": "ANALIZZA NUOVA DEMO",
      "SelectMatchTitle": "SELEZIONA PARTITA",
      "SelectMatchMsg": "Seleziona una partita a sinistra per vedere i dettagli",
      "Scoreboard": "TABELLONE",
      "DownloadDemo": "SCARICA DEMO",
      "WatchRoom": "GUARDA STANZA",
      "HeaderPlayer": "GIOCATORE",
      "HeaderKills": "UCCISIONI",
      "HeaderDeaths": "MORTI",
      "HeaderKD": "K/D",
      "HeaderADR": "ADR",
      "HeaderRating": "RATING",
      "MatchAnalyzed": "PARTITA ANALIZZATA",
      "AnalysisFailed": "Analisi fallita",
      "Settings": "IMPOSTAZIONI",
      "CS2Path": "Percorso installazione CS2",
      "CSGOPath": "Percorso installazione CSGO",
      "Steam64ID": "Steam 64 ID (Per scambi)",
      "SteamAPIKey": "Chiave API Web Steam",
      "DBUser": "Utente DB",
      "DBPassword": "Password DB",
      "LanguageLabel": "Lingua",
      "Save": "SALVA",
      "Submit": "INVIA",
      "SettingsSavedMsg": "Impostazioni salvate. Riavvia l'app.",
      "MapSelection": "SELEZIONE MAPPA",
      "PasteHubID": "MatchID@HostPeerID",
      "Map": "Mappa",
      "Connect": "CONNETTI",
    }
  };

  String get(String key) {
    if (_localizedValues.containsKey(currentLanguage)) {
      return _localizedValues[currentLanguage]![key] ?? key;
    }
    
    return _localizedValues["English"]?[key] ?? key;
  }
}